V1.3 show
AY2122S1-CS2103T-W08-2/tp pull request #168
Opened 2021-10-24 08:43 UTC by nbvannhi

Tests will be implemented in a separate PR.

Todos
- [x] fix font color
- [x]  remove `ShowAssessmentCommand` after merging with showing graph features

2021-10-24 08:59 UTC, zhing22 commented on src/main/java/seedu/address/model/student/Assessment.java
> +    }
my slight concern with this is someone may use getStatistics() without doing setStatistics() first, then they end up using outdated statistics. 

```suggestion
    public AssessmentStatistics getStatistics() {
        setStatistics();
        return statistics;
    }
```

2021-10-24 09:02 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/Assessment.java
> +    }
Oh right that makes sense 👍🏻

2021-10-24 14:23 UTC, ganhongyao requested changes
I think you also need to clear the infoDisplay panel once a new command is executed, if not it will be weird if the display persists when the user moves on to other commands. Also need to clear because an assessment has more info fields, thus leading to this result when I "show student" after "show assessment".

![image](https://user-images.githubusercontent.com/75519136/138598309-882532a7-980b-472b-b6c2-0f182947170a.png)
- The bottom 3 fields were left over from the assessment

Good job overall!

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        matchedAssessment.setStatistics();
```suggestion
```

since we are already calculating the statistics when we call `getStatistics`

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return name != null ? new NameContainsKeywordsPredicate(Arrays.asList(name.toString().split("\\s+")))
Should we ensure that a full name match instead of a partial match? Reason is because if we are searching by a part of a name, then if there are multiple students having that substring in their name, the command would require the user to enter ID to deconflict instead. I think this command should work differently from "search", and more like "add alloc".

![image](https://user-images.githubusercontent.com/75519136/138597204-3ee3744f-40e9-4770-aed7-a9365ad25d5f.png)

E.g. in this case, I should be able to just display Edwin Gray.

What do you think?

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +                || assessment == toCompare.assessment;
```suggestion
        boolean isNameEquals = name != null && name.equals(toCompare.name);
        boolean isIdEquals = id != null && id.equals(toCompare.id);
        boolean isAssessmentEquals = assessment != null && assessment.equals(toCompare.assessment);
```

since the respective `.equals` methods already do the reference equality check

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/Assessment.java
> +    private AssessmentStatistics statistics;
Is it necessary for this to be an attribute of an Assessment instance? Since we are essentially calculating the statistics each time we call `getStatistics`. I feel like an assessment shouldn't be tagged with a statistics object, and we should just do 

```java
return new AssessmentStatistics(this);
```
in `getStatistics`. This way, we don't need the `setStatistics` method as well.

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        // Should not happen since a Score must be between the minimum and maximum name (inclusive)
```suggestion
        // Should not happen since a Score must be between the minimum and maximum value (inclusive)
```

I think you accidentally find-and-replaced this 😅

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        assert min.isPresent();
I think we shouldn't assert it to be present, because there will be no elements if an assessment has no scores. I think we can handle that case explicitly? Same for `getMax`

2021-10-24 14:23 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +            return (sorted.get((int) half - 1)
I think we'll get an `IndexOutOfBounds` exception if there are no scores (and thus we try to get index -1)

2021-10-24 15:41 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return name != null ? new NameContainsKeywordsPredicate(Arrays.asList(name.toString().split("\\s+")))
My intention was to reuse the `NameContainsKeywordsPredicate` already implemented for `search` command, but I do agree that it would be weird to not be able to show the student due to **partial** duplicate naming like what you've pointed out.

Thus, how about if there is a full name match, the student will be shown immediately, otherwise if it is only partially matched, there will be a prompt to guide the user to use `show INDEX` to choose the student from the filtered list?

And do you think we should do similarly for `search` since wouldn't it be weird also to search full name `Edwin Gray` and `Edwin Gray` is at the bottom of the list (and the issue is more significant if this list is long)?

2021-10-24 15:43 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +                || assessment == toCompare.assessment;
The reference equality check is for checking the case where both fields of two objects are `null` so I suppose it is necessary?

2021-10-24 16:48 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/Assessment.java
> +    private AssessmentStatistics statistics;
> we are essentially calculating the statistics each time we call `getStatistics`

Although I am also aware of this, the statistics need to be passed into `InfoDisplay.java` so wouldn't it be weird if we pass both `Assessment` (to get assessment name) and `AssessmentStatistics` (to get the grade range, mean, median, etc) just to display the assessment info?

2021-10-24 16:50 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        assert min.isPresent();
Make sense 👍 Perhaps changing to `.orElse(0)` for empty score list case will do!

2021-10-24 16:52 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +            return (sorted.get((int) half - 1)
Indeed. Will resolve this ASAP!

2021-10-25 01:52 UTC, zhing22 commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        long size = sorted.size();
Jonas commented: Maybe the casting to `int` should be done here instead. I highly doubt we will have more than `max_int` data points.

2021-10-25 01:54 UTC, zhing22 commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        return sorted.get(((int) Math.ceil(x / 100.0 * size)) - 1);
Jonas commented: Risky. If there are no scores, then `size` = 0 and you'll be calling `get(-1)`
I think you'll need an explicit check here. Or use `Math.max(0, ...)`

2021-10-25 02:39 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +                || assessment == toCompare.assessment;
Hmm you're right (sorry!), in this case would 
```java
boolean isNameEquals = name == null ? toCompare.name == null : name.equals(toCompare.name);
```
better convey this intention? Same for the other fields

2021-10-25 02:44 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/Assessment.java
> +    private AssessmentStatistics statistics;
I think we can still just pass `Assessment` only, and in `InfoDisplay.java` we can call `getStatistics`, which calls the constructor and returns an instance of `AssessmentStatistics` (like in the snippet above). The only difference is that the `Statistics` instance is not a field of `Assessment`. 

Does that make sense?

2021-10-25 07:35 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/Assessment.java
> +    private AssessmentStatistics statistics;
That makes sense! Wonder why I couldn't think of it 🥲

2021-10-25 11:55 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        return sorted.get(((int) Math.ceil(x / 100.0 * size)) - 1);
Resolved this

2021-10-25 12:02 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        long size = sorted.size();
I did so because there might be the case where although `size` exceeds `max_int`, `(size + 1) / 2 - 1` does not, thus I think we gonna lose some data if doing typecast too early.

2021-10-25 12:30 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return name != null ? new NameContainsKeywordsPredicate(Arrays.asList(name.toString().split("\\s+")))
With that saying, I think we could resolve this by creating a new issue, as it involves the `search` command also.

What do you think? @ganhongyao

2021-10-25 14:49 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +            return (sorted.get((int) half - 1)
This is still not resolved for `getXPercentile` :/
![image](https://user-images.githubusercontent.com/75519136/138718112-957e1606-f7a4-46b3-8b45-289c07c4cdb5.png) for an assessment without any scores

2021-10-25 14:51 UTC, ganhongyao commented
Also, an assessment with no scores has its mean displayed as `NaN`. Can we set it to `Score.MIN_VALUE` as well?

2021-10-25 14:54 UTC, ganhongyao commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        return min.orElse(0.0);
```suggestion
        return min.orElse(Score.MIN_VALUE);
```

Instead of using magic numbers here. Same for `getMax`, `getMedian` (and for `getMean`, which is currently not handling the case for no scores)

2021-10-25 15:45 UTC, jonas-chow commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return name != null ? new NameContainsKeywordsPredicate(Arrays.asList(name.toString().split("\\s+")))
The thing with `search` is that it's more of a command used to find a student whose name you only vaguely remember.
`show` should be done with the user's full name/ID, since you should know for sure which student you want to be showing. So in that sense, it should be similar to `add alloc`.

Just my two cents..

2021-10-25 16:29 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +            return (sorted.get((int) half - 1)
Resolved it!

2021-10-25 17:02 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return name != null ? new NameContainsKeywordsPredicate(Arrays.asList(name.toString().split("\\s+")))
To follow-up in https://github.com/AY2122S1-CS2103T-W08-2/tp/issues/173

2021-10-25 17:02 UTC, ganhongyao approved these changes

2021-10-25 17:03 UTC, merged