V1.3 line graph
AY2122S1-CS2103T-W08-2/tp pull request #170
Opened 2021-10-24 17:00 UTC by zhing22

<img width="711" alt="Screenshot 2021-10-25 at 12 53 50 AM" src="https://user-images.githubusercontent.com/77109925/138604458-281c50a1-256e-4046-b22b-714e8c40fc9d.png">
tiny problem of the y-axis showing the 104 that Idk how to hide. <br>
has plans of adding candlestick chart.

2021-10-25 01:41 UTC, jonas-chow requested changes
A few minor changes required here and there

2021-10-25 01:41 UTC, jonas-chow commented on src/main/java/seedu/address/model/AddressBook.java
> +            if (student.isSameName(studentToMatch) || student.isSameStudent(studentToMatch)) {
Should this just be `isSameStudent`? Since `isSameName` can match multiple students.

2021-10-25 01:41 UTC, jonas-chow commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        // Should not happen since a Score must be between the minimum and maximum name (inclusive)
very minor, but not sure I get what this change is for... Scores have names??

2021-10-25 01:41 UTC, jonas-chow commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        long size = sorted.size();
Maybe the casting to `int` should be done here instead. I highly doubt we will have more than `max_int` data points.

2021-10-25 01:41 UTC, jonas-chow commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        return sorted.get(((int) Math.ceil(x / 100.0 * size)) - 1);
Risky. If there are no scores, then `size` = 0 and you'll be calling `get(-1)`
I think you'll need an explicit check here. Or use `Math.max(0, ...)`

2021-10-25 01:46 UTC, zhing22 commented on src/main/java/seedu/address/model/AddressBook.java
> +            if (student.isSameName(studentToMatch) || student.isSameStudent(studentToMatch)) {
isSameStudent only checks the ID, but use can input both name and ID. but its also depends on what Vani wrote, we need to fix integrating our code after both sides merged

2021-10-25 01:46 UTC, zhing22 commented on src/main/java/seedu/address/model/student/AssessmentStatistics.java
> +        // Should not happen since a Score must be between the minimum and maximum name (inclusive)
this part is mirroring changes on Vani's side. she changed the variable from value to name for clarity.

2021-10-25 01:49 UTC, zhing22 commented
Actually the AssessmentStatistics is all from Vani's part, i just copied all her code in because I need her function and she need my functions :( so i'll just assume I'll merge this first. for the last two comments i'll remember to let her know

2021-10-25 01:50 UTC, merged

2021-10-25 16:28 UTC, nbvannhi commented on src/main/java/seedu/address/model/student/StudentStatistics.java
> +        return dataSet;
Just notice that this gives a warning for uncheck assignments when running the app  so you may want to resolve it (or suppress the warning) 👀 

![image](https://user-images.githubusercontent.com/63232300/138733498-e52c88f6-d304-4b30-96ea-f4d111c62b0a.png)

2021-10-26 03:23 UTC, zhing22 commented on src/main/java/seedu/address/model/AddressBook.java
> +            if (student.isSameName(studentToMatch) || student.isSameStudent(studentToMatch)) {
resolved

2021-10-26 03:45 UTC, zhing22 commented on src/main/java/seedu/address/model/student/StudentStatistics.java
> +        return dataSet;
ok thanks for pointing out!