Show student card to resolve naming conflicts
AY2122S1-CS2103T-W08-2/tp pull request #174
Opened 2021-10-25 17:03 UTC by leonghongfai

closes #163 
The testing part please do take a look, I am not sure if this might be the best way to test for it. The current assertCommandFailure will always result in a failed test as it does not account for the FilteredList change.

2021-10-25 21:29 UTC, nbvannhi requested changes
Perhaps showing students with duplicate naming can be done within the `execute` method itself, instead of creating a new util class just for one method.

W.r.t. testing, I think it is correct but can improve to also cover integration testing.

Good job overall!

2021-10-25 21:29 UTC, nbvannhi commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    }
I would suggest creating an assertion method similar to `assertCommandSuccess`, such as
```java
assertCommandFailure(Command command, Model actualModel, String expectedMessage, Model expectedModel)
```
This would allow **integration testing** together with the current unit testing. Perhaps taking a look at `assertCommandSuccess` to follow the convention would be a good idea.

2021-10-25 21:29 UTC, nbvannhi commented on src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java
> +        assertCommandFailureWithFilteredListChange(addAllocCommand, model, expectedMessage, expectedList);
Wouldn't it be better to also cover **integration testing**? To be more specific, you can create a `Model` and **manually execute** the command on it (i.e., edit the filtered student list), then assert by comparing the two models with

```java
assertCommandFailure(Command command, Model actualModel, String expectedMessage, Model expectedModel)
```

I suggest taking a look at the `execute_addAllocByName_success()` to get a better idea :) Same for `AddScoreCommandTest` and `AddGroupCommandTest`

2021-10-25 21:29 UTC, nbvannhi commented on src/main/java/seedu/address/commons/util/SameNameConflictUtil.java
> +public class SameNameConflictUtil {
Hmm idt it's necessary to create a new class for only one method 🤔
Can refer to my suggested approach in `AddAllocCommand`!

2021-10-25 21:29 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/AddAllocCommand.java
> +            showStudentsWithNameConflicts(model, studentsToEdit);
Maybe this will do

```suggestion
            List<String> matchedIds = matchedStudents.stream()
                                    .map(Student::getId).map(ID::getValue)
                                    .collect(Collectors.toList());
            Predicate<Student> predicate = new IdContainsKeywordsPredicate(matchedIds);
            model.updateFilteredStudentList(predicate);
```

Same for `AddScoreCommand` and `AddGroupCommand`

2021-10-25 21:29 UTC, nbvannhi commented on src/main/java/seedu/address/commons/util/SameNameConflictUtil.java
> +        Predicate predicate = new IdContainsKeywordsPredicate(keywordsList);
Not really related but be careful not to use raw type :) Can put `Predicate<Student>` instead

2021-10-26 05:27 UTC, leonghongfai commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    }
The problem with following the assertCommandSuccess model is the filtered list check. To get the correct filtered list, I am basically doing the same thing to the expected model as i did with the actual model, which I don't think makes a lot of sense. It's like making the same model twice and comparing them. Thats why i made a new method which takes in a filteredlist as input, so I can check the actual filteredlist versus what I know should be the correct filtered list

2021-10-26 05:33 UTC, leonghongfai commented on src/main/java/seedu/address/commons/util/SameNameConflictUtil.java
> +public class SameNameConflictUtil {
Im not sure how the group came to the conlusion to put this method under util actually. But I agree that it can be done under each respective command.

2021-10-26 10:09 UTC, nbvannhi commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    }
I suppose the task of filtering the list is done within the command itself? In other words, after the command is executed the model's filtered list will be updated accordingly.

2021-10-26 15:21 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/AddAllocCommand.java
> +            showStudentsWithNameConflicts(model, studentsToEdit);
Sorry I didn't comment on this earlier, but I think what Vani suggested here may be a better approach than `SameNameConflictUtil::showStudentsWithNameConflicts`, since we're kind of doing too many things at once within that method.

On top of that, while I was working on #173, I think instead of creating a `Predicate` from the IDs of the matched students, would it be better to have a `NameEqualsPredicate` with the name argument that the user passed, then calling `model.updateFilteredStudentList` with that predicate? I feel like that's more natural

What do you guys think? @nbvannhi @leonghongfai

2021-10-26 17:10 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AddAllocCommand.java
> +            showStudentsWithNameConflicts(model, studentsToEdit);
@ganhongyao @nbvannhi I think its more natural too, I only did it via IDs as the `NameContainsKeywordsPredicate` is unable to match the whole name fully. If we are fully agreeable, I can change it accordingly.

2021-10-26 17:22 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/AddAllocCommand.java
> +            showStudentsWithNameConflicts(model, studentsToEdit);
I agree too 👍🏻

2021-10-26 18:54 UTC, nbvannhi approved these changes
LGTM 👍🏻

2021-10-26 18:55 UTC, merged