V1.3 show group
AY2122S1-CS2103T-W08-2/tp pull request #177
Opened 2021-10-26 01:37 UTC by nbvannhi

Tests will be implemented in a separate PR.

This PR will be ready for a complete review once displaying statistics graph for groups feature is implemented as some code is commented out now to be able to compile.

Please do note that the branch `v1.3-show-INDEX` is merged into this branch `v1.3-show-group` so some changes belong to the show INDEX feature :(

2021-10-26 08:04 UTC, ganhongyao commented
@nbvannhi Could you merge the latest master into this branch so that there are lesser diffs? Thanks!

2021-10-26 08:29 UTC, ganhongyao requested changes

2021-10-26 08:29 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return new CommandResult(MESSAGE_SUCCESS, info); // delete when merging
Is this referring to this PR https://github.com/AY2122S1-CS2103T-W08-2/tp/pull/178 ?

2021-10-26 08:29 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> -        }
I think you accidentally removed the changes in the other PR while merging

2021-10-26 08:29 UTC, ganhongyao commented on src/main/java/seedu/address/logic/parser/ShowCommandParser.java
> +                : new ShowCommand(ParserUtil.parseGroup(argMultimap.getValue(PREFIX_GROUP).get()));
I don't think we can assume that when all other prefixes are not present group will definitely be present. Currently, if I just execute "show", I get an exception because we call `get` on `argMultimap.getValue(PREFIX_GROUP)`, which is not present.

2021-10-26 08:29 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
>      }
Would it be cleaner if we just do `setIndex(index)` in this constructor instead of calling the overloaded constructor with `null`s? Same for the others

2021-10-26 08:39 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        return new CommandResult(MESSAGE_SUCCESS, info); // delete when merging
Yep!

2021-10-26 08:42 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> -        }
Ah actually no. When I did this show graph part I realised that the `Index` field is redundant since `Info` is responsible for showing stats either a `Student`, an `Assessment` or a `Group`, but not an `Index`. And I forgot to switch branch and make a separate commit for that..

2021-10-26 08:50 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
>      }
Make sense! Resolving this

2021-10-26 08:53 UTC, nbvannhi commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
>      }
Resolved!

2021-10-26 09:33 UTC, ganhongyao commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> -        }
Oh right okay!

2021-10-26 09:43 UTC, nbvannhi commented on src/main/java/seedu/address/logic/parser/ShowCommandParser.java
> +                : new ShowCommand(ParserUtil.parseGroup(argMultimap.getValue(PREFIX_GROUP).get()));
Resolved!

2021-10-26 11:47 UTC, zhing22 commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        // GroupStatistics statistics = new GroupStatistics(matchedGroup);
pass in model as parameters
```suggestion
        GroupStatistics statistics = new GroupStatistics(matchedGroup, model);
```

2021-10-26 17:15 UTC, nbvannhi commented
@ganhongyao it's ready for review now!

2021-10-27 03:01 UTC, ganhongyao approved these changes

2021-10-27 03:02 UTC, ganhongyao commented
LGTM! Nice

2021-10-27 03:02 UTC, merged