Add alias functionality
AY2122S1-CS2103T-W08-2/tp pull request #179
Opened 2021-10-26 06:14 UTC by jonas-chow

Closes #159 
Add alias functionality

Note: alias is limited to single word aliases only. (Otherwise parsing is seriously quite a nightmare)

Things not done yet: (But I believe it's safe to merge anyway if you're reviewing this early enough)
- [x] Add more tests to AddressBookParserTest
- [x] Update ugdg

2021-10-26 13:47 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +
alias add student -> as is the wrong format if i am not looking at this wrongly.
Should be "alias as -> add student instead"

2021-10-26 14:19 UTC, leonghongfai requested changes
Nicely done with the tests!

2021-10-26 14:19 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            parser.addAlias(alias);
I am not sure if this is intended but lets say i add "as" as an alias for add student command. Then I add "addstud" as alias for student command after, both aliases still work. Would it be a better idea to remove the old alias?

2021-10-26 14:19 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            return new CommandResult(String.format(MESSAGE_REMOVE_SUCCESS, alias.getAliasWord()));
actually is there a need for this if block, since if it is redundant, AliasCommandParser#parse will already throw a ParseException
` 
        if (isValidCommandWord(aliasWord) && parser.getAlias(aliasWord).isEmpty()) {
            throw new ParseException(AliasCommand.MESSAGE_OVERWRITE_DEFAULT);
        }`
lines 41-44 for easy reference

2021-10-26 14:19 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            return new CommandResult(String.format(MESSAGE_REMOVE_SUCCESS, alias.getAliasWord()));
ie the block will not be enterred from my understanding.

2021-10-26 14:19 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            parser.addAlias(alias);
Also, the error message when i type "as" gives the error message from add student command, which includes "Example: add student -n John Doe -i E0543948 -g T01A-t friends -t owesMoney". Would it be possible to change it such that if there is an alias present, "as" in this case, the error message changes to "Example: as -n..."

2021-10-26 15:52 UTC, jonas-chow commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            return new CommandResult(String.format(MESSAGE_REMOVE_SUCCESS, alias.getAliasWord()));
This one is more of a special case where you do alias -> alias to remove the alias.
When the alias already exists, so `parser.getAlias(aliasWord)` is not empty and the `ParseException` won't throw.

2021-10-26 15:52 UTC, jonas-chow commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +
You're right. Thanks for pointing this out.

2021-10-26 15:56 UTC, jonas-chow commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +            parser.addAlias(alias);
With the current implementation, it is quite difficult to change the error message as I'm basically just replacing the alias with the existing word and parsing again.

Allowing 2 aliases for the same command is intentional. In fact, you are able to:
1. Assign "as" to "add student"
2. Assign "addstud" to "as"
3. "addstud" will then also point to "add student"

A weird thing that this leads to though, is that reassigning "as" to some other command won't reassign "addstud". So it's not exactly that addstud points to as. (Aliases are treated as primitive values instead of compound values, if that's clear)

Not sure if this implementation is the best, would be nice to have more opinions.

2021-10-27 02:46 UTC, zhing22 commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +
Hi, currently the command format is `alias <new_alias> -> <existing_command>`, the syntax is very different from how our other commands are so i'm a bit reluctant. I suggest something like `alias -c <existing_command> -ali <new_alias>`. What do ya'll think?

2021-10-27 09:11 UTC, leonghongfai approved these changes
Other than the syntax comment from Zhi Ying, LGTM. Feel free to merge after addressing that comment!

2021-10-27 09:11 UTC, leonghongfai commented on src/main/java/seedu/address/logic/commands/AliasCommand.java
> +
Actually, I feel the arrow does make quite a bit of sense, but then again its just syntax. @jonas-chow what do you think?

2021-10-27 10:33 UTC, jonas-chow commented
One last review would be nice. I tested it myself, so it should work
Basically, command prefix is `-c`, alias prefix is `-as`. "Default" syntax is `alias -c <command> -as <alias>`.

Also, @leonghongfai was actually right. I the `isRedundant` thing wasn't being reached. I fixed that with a short circuit in the parser so removing aliases are possible again.

2021-10-28 08:25 UTC, leonghongfai approved these changes
LGTM. Everything seems to work fine.

2021-10-28 08:25 UTC, merged