V1.4 fix inconsitent error messages for invalid index
AY2122S1-CS2103T-W08-2/tp pull request #244
Opened 2021-11-02 07:24 UTC by nbvannhi

Closes #223

2021-11-02 14:11 UTC, zhing22 commented
yes could you please help to fix all other commands that uses <index>? (namely show, delete, and edit)

also since you are working on it could you take over #217 too? its about error message for negative numbers and 0.

Thank you!! <3

2021-11-02 14:11 UTC, jonas-chow reviewed
I feel like the error message is too general here.
Things like `show a` and `show -1` will give the same error message, but the error message doesn't really tell the user how they should be changing their input to make it valid.

2021-11-02 14:11 UTC, jonas-chow commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +        if (index.getOneBased() < 1 || index.getZeroBased() >= students.size()) {
The added clause will never be true. `ParseIndex` takes care of this case already.

2021-11-02 14:11 UTC, jonas-chow commented on src/main/java/seedu/address/logic/parser/ShowCommandParser.java
> +            throw new ParseException(MESSAGE_INVALID_STUDENT_DISPLAYED_INDEX);
Perhaps we need a more descriptive error message than "The student index provided is invalid".
I suggest we split the error message into the following cases:

* Inputs that contain characters that are not digits: "Index is not a positive unsigned integer."
* Inputs that only contain digits
    * Those that `parseInt` properly: 
        * If 0: "Index is not a positive unsigned integer."
        * If greater than student list size: "Index is too large"
        * Else: Executes properly
    * Doesn't `parseInt`: Above `MAX_INT`: "Index is too large"

Would be nice if you could rewrite the `parseIndex` function in `ParserUtil.java` to implement these (except perhaps the greater than student list size one)

2021-11-04 17:26 UTC, jonas-chow requested changes
`show 1` doesn't work!!!

2021-11-04 17:35 UTC, jonas-chow approved these changes
There was an issue with show command not working with indices. I fixed it by negating a condition. Otherwise, lgtm.

2021-11-04 18:46 UTC, nbvannhi commented
> 
> 
> `show 1` doesn't work!!!

Oh I fixed it later but forgot to push... Tks anw!

2021-11-04 18:46 UTC, merged